### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Felipe-Perez-Ferraro** [Godedict/Portfolio-Setup#11]
Impressive use of javascript in your project, so very simple and effective. And your css styling is really well. Talking about your index file you used a lot of semantic tags so that is perfect. Nice job

**Comment by Rysth** [comment]
Excellent job, @Godedict!.

## Impressive Features 💯 

✅ Excellent use of JavaScript and simple but effective code.
✅ Nice hierarchy and use of accessibility to enhance the code itself.
✅ Good definitions of classes within your `styles.css` file.

## Suggestions ⭐ 

- Should you try to use common classes within your `styles.css` file, which can help you to maintain a flexible project for the future.
